### ISSUE TITLE
minor fixes

### ISSUE THREAD

**Issue by MaryLu28** [ShadowManu/fundabitat#11]
- change the order of the images in programs -----> Done
- change text align ----> Done
- indenting year in programs ----> Done
- delete IARTES in Relations ----> Done
- change font style to Century Gothic --> moved to #15 
- boldface in Areas ----> Done
- links in Relations ----> Done
- fix images size moved to #26
  - areas tematicas
  - publicaciones
  - programas (rounded edges)

**Comment by ShadowManu** [comment]
Change font is moved to the new issue #15.

**Comment by ShadowManu** [comment]
try to finish this issue to close it. If you find more new "small fixes", treat them on a new pertaining issue.

**Comment by MaryLu28** [comment]
images to fix: moved to #26
- back rounded edges on all programs images
- /src/assets/images/publications/Juego-Educativo-MR.png
- /src/assets/images/publications/RUEDA-MUNDO.png
- /src/assets/images/publications/RUEDA-VENEZUELA-copia-1.png
- /src/assets/images/publications/Tecnologías.-Apropiadas-y-Apropiables.png

**Comment by ShadowManu** [comment]
pending changes will be solved on mentioned issues.
