### ISSUE TITLE
minor fixes 2

### ISSUE THREAD

**Issue by MaryLu28** [ShadowManu/fundabitat#26]
- fix images size
  - /src/assets/images/publications/juego-educativo-mr.png
  - /src/assets/images/publications/rueda-mundo.png
  - /src/assets/images/publications/rueda-venezuela.png
  - /src/assets/images/publications/tecnologias.-a-y-a.png
- decrease the size of the logos of ANAR and RETAM in home -------> Done
- alignment change the description of FUNDABITAT in home (I'll explain later) -----> Done
- put in bold capital letters "Fundabitat" and delete "además" in the description in home -------> Done
- add countries in programs ------> Done

**Comment by MaryLu28** [comment]
@shadowmanu do this ----> fix images size

**Comment by ShadowManu** [comment]
closed this on 787e30db1cdef5520452afa633fe4b3744cedbf2
